### PR TITLE
chore: add docs for known vulnerabilities

### PR DESCRIPTION
**Pull request by bethesque**
So we don't have to repeat ourselves each time, we should have a page that lists our known vulnerabilities and their mitigations. I'm definitely missing some for bootstrap, but I'll add them as they come up. The most recent people who complained about them didn't include the CVEs.

* What should the page be called?
* Any extra info?

### CODE REVIEW

**Comment by uglyog** [comment]
Security audit report?

**Comment by Inksprout** [comment]
title ideas: "Vulnerabilities" or more generally "Dependency Management". If they're coming across vulnerabilities when using it then titling the page that might be the fastest way for them to reach this explanation. Do we want to suggest a process for them to raise other vulnerabilities with us? Still probably just contacting us through the usual channels but we could request the CVE to be included

**Review by Inksprout — APPROVED** [review]

**Comment by bethesque** [comment]
> but we could request the CVE to be included

👍🏽

**Comment by bethesque** [comment]
> Security audit report?

Yes, good idea. Not sure which ones though, and we'd need to keep them up to date. I guess the output of bundler/npm/trivy could be an audit report?

**Comment by bethesque** [comment]
Or do you mean the pen test report Ron?

**Comment by uglyog** [comment]
No, the page name. If we call it the Pactflow security audit report, it sounds important. It can just be a curated list of issues with mitigation.

**Pull request merged**
