### PR TITLE
chore: add release notes for 1.27.0

### PR DESCRIPTION
**Pull request by bethesque**

### CODE REVIEW

**Comment by mefellows** [comment]
My understanding is that the current version of the SMV in 1.26.0 is 12.3.0, so there should be numerous features/fixes since then: https://github.com/pactflow/swagger-mock-validator/compare/12.3.0..14.1.0?diff=unified

I  believe that includes (taken from the changelog):

```
# [14.1.0](https://github.com/pactflow/swagger-mock-validator/compare/14.0.0...14.1.0) (2023-08-21)


### Bug Fixes

* handle nested allOf ([#43](https://github.com/pactflow/swagger-mock-validator/issues/43)) ([41cb25d](https://github.com/pactflow/swagger-mock-validator/commit/41cb25d1b2a0ed5fa58e42ba6901fd9290a402dd))



# [14.0.0](https://github.com/pactflow/swagger-mock-validator/compare/13.3.0...14.0.0) (2023-08-04)


### Features

* explicity set additionalProperties to false ([82f2a3b](https://github.com/pactflow/swagger-mock-validator/commit/82f2a3b9e5c9bf699969b301c2e62a59906a1b79))



# [13.3.0](https://github.com/pactflow/swagger-mock-validator/compare/13.2.0...13.3.0) (2023-07-28)


### Bug Fixes

* handle exclusiveMinimum/exclusiveMaximum in bodies ([#37](https://github.com/pactflow/swagger-mock-validator/issues/37)) ([fd4dee0](https://github.com/pactflow/swagger-mock-validator/commit/fd4dee0a3e96affbb041d30856e63a0b1a841b33))



# [13.2.0](https://github.com/pactflow/swagger-mock-validator/compare/13.1.0...13.2.0) (2023-07-04)


### Bug Fixes

* incorrect decoding of pact v4 bodies ([#33](https://github.com/pactflow/swagger-mock-validator/issues/33)) ([0a7f140](https://github.com/pactflow/swagger-mock-validator/commit/0a7f140d302df0a6f2249994a9c5d6b40c44b53f))


### Features

* allow polymorphic inheritance in request bodies ([#34](https://github.com/pactflow/swagger-mock-validator/issues/34)) ([beb128b](https://github.com/pactflow/swagger-mock-validator/commit/beb128b43432033e319ef4f7559106202c3956b7))



# [13.1.0](https://github.com/pactflow/swagger-mock-validator/compare/13.0.0...13.1.0) (2023-06-30)


### Features

* improve support for allOf, anyOf, oneOf ([#32](https://github.com/pactflow/swagger-mock-validator/issues/32)) ([8035cce](https://github.com/pactflow/swagger-mock-validator/commit/8035cce8da493a1d01de4a003f713016c3fcb937))



# [13.0.0](https://github.com/pactflow/swagger-mock-validator/compare/12.3.0...13.0.0) (2023-06-28)

### Features

* upgrade Ajv from v6 to v8 ([5a17818](https://github.com/pactflow/swagger-mock-validator/commit/5a1781824239367ffed35afd01748cba77d8b75e))
* ```

**Comment by vwong** [comment]
Yeah, 2 major versions since. Thanks @mefellows for the changelog

**Comment by bethesque** [comment]
Updated.

**Comment by bethesque** [comment]
PACT-1288

**Review by mefellows — APPROVED** [review]

**Review by YOU54F — APPROVED** [review]

**Pull request merged**
