### PR TITLE
feat: add docs for SCIM role migration

### PR DESCRIPTION
**Pull request by bethesque**
This can be copied in to the relevant page when we do the next release.

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks. What happens if they don't follow the instructions and a role `SCIM` remains - will the migrations job fail?

**Comment by bethesque** [comment]
I've just updated the migration to rename any existing `SCIM` role to `SCIM (Deprecated)`

**Comment by bethesque** [comment]
So it won't fail.

**Comment by mefellows** [comment]
Thanks, that seems safer ;)

**Pull request closed without merging**
